services:

  api:
    build: .
    container_name: real-time-chat-api
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    depends_on:
      - mongodb
      - redis
    restart: unless-stopped

  mongodb:
    image: mongo:8
    container_name: real-time-chat-mongodb
    ports:    
      - "27018:27017" 
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: real-time-chat-redis
    restart: unless-stopped

volumes:
  mongo_data: